package queryparser;

public enum Validation {
	NULL_QUERY,
	
	S1_NULL_CHECK,
	S1_STARTS_ENDS_WITH,
	S1_EMPTY_QUERY,
	S1_ZERO_BOUNDARY_CHARS,
	S1_ODD_BOUNDARY_CHARS,
	
	S2_NULL_CHECK,
	S2_CONTAINS_KEY_VAL_DELIM,
	
	S3_NULL_CHECK,
	S3_KEYS_WITHIN_ALLOWED_KEYS,
	S3_BOUNDARY_CHARS,
	
	S4_NULL_CHECK
}
